engines:
  tslint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
tslint:
  enabled: true
  channel: beta
  config: tslint.json
ratings:
  paths:
  - "**.ts"
exclude_paths:
- node_modules/**/*
- typings/**/*
- src/**/*.css