engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  eslint:
    enabled: true
  csslint:
    enabled: false
ratings:
  paths:
  - "**.ts"
exclude_paths:
- node_modules/**/*
- typings/**/*
- src/**/*.css