language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
 — sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

env:
  CHROME_BIN=chromium-browser
  DISPLAY=:99.0

notifications:
  email:
    recipients:
    on_success: change
    on_failure: always