# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/front-taxi4fun
    docker:
      - image: circleci/node:7-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - angular-cli-cache-{{ checksum "package.json" }}
            - angular-cli-cache-
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-

      - run: sudo npm install -g @angular/cli

      - save_cache:
          key: angular-cli-cache-{{ checksum "package.json" }}
          paths:
              - /usr/local/lib/node_modules/@angular/cli/

      - run: sudo npm install -g codeclimate-test-reporter

      - run: npm install

      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
              - ./node_modules

      - run: ng build --aot --no-progress

      - run: ng test --watch=false --code-coverage

      - run: codeclimate-test-reporter < coverage/lcov.info

